# Generated by Django 4.2.6 on 2023-11-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_dailydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldata',
            old_name='value',
            new_name='goldValue',
        ),
    ]
